### ISSUE TITLE
veliava

### ISSUE THREAD

**Issue by fordnox** [seima/viskas#8]
https://www.15min.lt/m/id/aktualu/lietuva/15min-paaiskina-kada-butina-prie-namu-issikelti-lietuvos-veliava-ir-kas-gresia-to-nepadarius-56-839654

**Comment by nxo** [comment]
http://www.altreklama.lt/veliavos/veliavu-kotai-stovai-ir-laikikliai/
yra tvirtinimas prie stulpo
